name:  gaurodan
title:  Gaurodan
version: "1.1"
summary:   Nice shooter
description: |
  Long forgotten is the legend of Gaurodan, the bird of thunder, and his fight with Guayota, the fire beast. But now mankind has discovered the egg of Guayota within Mount Teide, and it is only a matter of time until Gaurodan returns from the sky to fight the beast and punish us for awakening his ancient enemy. Fly around the Canary Islands as Gaurodan, and destroy cities, armies and colossal creatures in your path throught this frantic shmup, created for the lovers of classic games that require mastering. You'll need some mastering to play this game because controls are not the usual: you have two buttons to shoot air-air and air-ground, and you can't stop moving in the air. Guarodan is inspired by early titles like Defender, Choplifter or Sky Kid in terms of gameplay, and has a similar production style to other arcade games like Commando, Gyrodine or 1942.

grade: stable
icon: gaurodan_icon.png

base: core18
confinement: strict

architectures:
  - build-on: amd64
  - build-on: i386

environment:
  WINEDLLOVERRIDES: "$WINEDLLOVERRIDES;mscoree,mshtml="    # Prevent pop-ups about Wine Mono and Wine Gecko
  SOMMELIER_STRICT: "1"                                    # Make Sommelier exit when unset variable is used. (useful to find bugs in sommelier)

apps:
  gaurodan:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: "Gaurodan.exe"
      #INSTALL_EXE: "$SNAP/Blockout25_setup.exe"
      #INSTALL_FLAGS: "/S"
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - cups
  # The wine command can be used to run applications inside the wine
  # environment that this snap uses.
  #
  # For example, users can configure the wine environment of this snap
  # by running `myapp.wine winecfg`.
  wine:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier
    plugs:
      - home
      - network
      - network-bind
      - removable-media
      - cups
 # The winetricks command can be used to run winetricks inside the wine
  # environment that this snap uses.
  winetricks:
    extensions: [ gnome-3-28 ]
    command: bin/sommelier winetricks
    plugs:
      - network

parts:
  installer:
    plugin: dump
    source: ./

  # The sommelier script helps you snap Windows applications using Wine. It 
  # initializes and configures Wine and installs the Windows application.
  sommelier:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git

# These plugs are used to connect the snap to the wine runtime.
plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-5-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-5-stable

